version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - durationcheck
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true
